const problem=[
    {
        id:1,
        name:"Personalized Kundali",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Kundli-Match.png",
        desc:"Get A Personalized Kundali As Per Your Birth Chart And A  Future Prediction For Coming 20 Years.",
        link:"https://wa.me/918018776502",
    },
    {
        id:2,
        name:"Call Consultation",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Consultancy.png",
        desc:"You Can Get A One-To-One CAll Consultation To Clarify All Your Doubts Regarding Your Astrology.",
        link:"https://wa.me/918018776502",
    },
    {
        id:3,
        name:"Horoscope",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Aries-1.png",
        desc:"Know Your Horoscope/Rashi For A Particular Person About The Position Of Stars And Planets.",
        link:"https://wa.me/918018776502",
    },
    {
        id:4,
        name:"DOB Analysis",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Kundli-Match.png",
        desc:"You Can Get A Formula For Your LIfe Success By Getting The Steps Of DOB Analysis.",
        link:"https://wa.me/918018776502",
    },
    {
        id:5,
        name:"Kundli Matching",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Kundli-Match.png",
        desc:"Make the Kundali Matched With Your Partner To Avoid After Marriage Problems",
        link:"https://wa.me/918018776502",
    },
    {
        id:6,
        name:"Vastu Consultation",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Vastu-Online.png",
        desc:"Make Vastu Design Or Vastu Correction To Avoid The Bad Effects Of Vastu.",
        link:"https://wa.me/918018776502",
    },
    {
        id:7,
        name:"Numerology",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Numerology-.png",
        desc:"It is the symbolic meaning of numbers that shows the influence of different aspects of life.",
        link:"https://wa.me/918018776502",
    },
    {
        id:8,
        name:"Palmistry",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Palmistry.png",
        desc:"Know Your Ups And Downs of Life From The Different Lines Present in Your Palm.",
        link:"https://wa.me/918018776502",
    },
    {
        id:9,
        name:"Varsh Phal",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Lal-Kitab.png",
        desc:"An Yearly Prediction And An Insight To Your Life For Coming One Year.",
        link:"https://wa.me/918018776502",
    },
    {
        id:10,
        name:"Lal Kitab",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Lal-Kitab.png",
        desc:"Get The Solution of Your Problems By Following The Ancient Technology Of Lal Kitab.",
        link:"https://wa.me/918018776502",
    },
    {
        id:11,
        name:"Online Puja",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Online-Puja.png",
        desc:"You Can Make YOur Rituals Online Without Visiting To Us With Your Comfort Space And Time.",
        link:"https://wa.me/918018776502",
    },
    {
        id:12,
        name:"Gochar",
        img:"https://astrologeraswinipanda.com/wp-content/uploads/2024/07/Gochar.png",
        desc:"Understand How Gochar Influence Our Life Through all Aspects  Like. Carrer, Marriage, Finance And Health Etc..",
        link:"https://wa.me/918018776502",
    },
]
export default problem;